[package]
name = "termcolor_output_impl"
version = "1.0.0-rc.3"
authors = ["Cerberuser"]
edition = "2018"
description = "Implementation crate for colored! macro."
license = "MIT"

[lib]
proc-macro = true

[dependencies]
